"""Check built archive contents against the checkout and documented usage.

Run after ``uv build``. This checks the root distribution only and performs no
installation, extraction or network requests.
"""

import argparse
import posixpath
import re
import tarfile
import tomllib
import zipfile
from email.parser import BytesParser
from pathlib import Path, PurePosixPath

ROOT = Path(__file__).resolve().parents[1]


def verify_distribution(dist_dir: Path) -> None:
    """Validate source parity, archive boundaries, metadata and local document links.

    Args:
        dist_dir: Directory containing the wheel and source archive for this version.

    Raises:
        ValueError: An artifact omits or changes required content or metadata.
        OSError: A required archive cannot be read.
    """
    project = tomllib.loads((ROOT / "pyproject.toml").read_text())["project"]
    name, version = project["name"].replace("-", "_"), project["version"]
    stem = f"{name}-{version}"
    with tarfile.open(dist_dir / f"{stem}.tar.gz") as archive:
        source = {}
        for member in archive.getmembers():
            path = PurePosixPath(member.name)
            if path.is_absolute() or ".." in path.parts or path.parts[0] != stem:
                raise ValueError(f"Unexpected source archive path: {member.name}")
            if member.isdir():
                continue
            if not member.isfile():
                raise ValueError(f"Unexpected source archive member type: {member.name}")
            key = str(path.relative_to(stem))
            if key in source:
                raise ValueError(f"Duplicate source archive member: {key}")
            source[key] = archive.extractfile(member).read()
    with zipfile.ZipFile(dist_dir / f"{stem}-py3-none-any.whl") as archive:
        if len(archive.namelist()) != len(set(archive.namelist())):
            raise ValueError("Duplicate wheel members")
        wheel = {name: archive.read(name) for name in archive.namelist()}
    info = f"{stem}.dist-info/"
    for path in wheel:
        if not path.startswith(("research_bridge/", info)) or ".." in PurePosixPath(path).parts:
            raise ValueError(f"Unexpected wheel path: {path}")
    expected = {
        str(path.relative_to(ROOT / "src")): path.read_bytes()
        for path in (ROOT / "src/research_bridge").rglob("*.py")
    }
    actual = {path: data for path, data in wheel.items() if path.startswith("research_bridge/")}
    if actual != expected:
        raise ValueError("Wheel code differs from checkout source")
    for path, data in expected.items():
        if source.get(f"src/{path}") != data:
            raise ValueError(f"Source archive code differs from checkout: {path}")
    for path, data in source.items():
        if path.endswith(".pyc") or "__pycache__" in PurePosixPath(path).parts:
            raise ValueError(f"Generated bytecode in source archive: {path}")
        if path != "PKG-INFO" and (
            not (ROOT / path).is_file() or (ROOT / path).read_bytes() != data
        ):
            raise ValueError(f"Source archive content differs from checkout: {path}")
        if path.endswith(".md"):
            for target in re.findall(r"\]\(([^)]+)\)", data.decode()):
                if "://" in target or target.startswith("#"):
                    continue
                resolved = posixpath.normpath(
                    str(PurePosixPath(path).parent / target.split("#")[0])
                )
                if resolved not in source:
                    raise ValueError(
                        f"Broken source archive documentation link: {path} -> {target}"
                    )
    for path in (
        "README.md",
        "pyproject.toml",
        "uv.lock",
        "Dockerfile",
        ".dockerignore",
        ".env.example",
        "tests/offline_journey.py",
        "tests/runtime_smoke.py",
        "scripts/verify_distribution.py",
    ):
        if path not in source:
            raise ValueError(f"Missing documented distribution input: {path}")
    metadata = BytesParser().parsebytes(wheel[info + "METADATA"])
    if metadata["Name"] != project["name"] or metadata["Version"] != version:
        raise ValueError("Wheel identity does not match the project")
    requirements = metadata.get_all("Requires-Dist", [])
    if not any(item.startswith("httpx") and ";" not in item for item in requirements):
        raise ValueError("Core HTTP dependency is missing")
    for dependency in ("fastapi", "uvicorn"):
        matches = [item for item in requirements if item.startswith(dependency)]
        if len(matches) != 1 or not re.search(r""";\s*extra\s*==\s*(['"])server\1$""", matches[0]):
            raise ValueError(f"Server dependency must remain optional: {dependency}")
    if any(";" not in item and not item.startswith("httpx") for item in requirements):
        raise ValueError("Unexpected core dependency")
    entrypoints = wheel[info + "entry_points.txt"].decode()
    for command, target in project["scripts"].items():
        if f"{command} = {target}" not in entrypoints:
            raise ValueError(f"Missing installed command: {command}")
    print(f"Distribution verified: {len(source)} source files, {len(wheel)} wheel files.")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dist-dir", type=Path, default=ROOT / "dist")
    verify_distribution(parser.parse_args().dist_dir)
